config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/', to: 'home#index'
  get '/github/repositories', to: 'github/repositories#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/github/repositories_controller.rb
class Github::RepositoriesController < ApplicationController
  RESULTS_PER_PAGE = 10
  
  before_action :check_required_params
  before_action :set_page_params

  def index
    @page = params[:page].to_i
    @query = params[:query]
    @repositories = Github::Repository.search_repositories(search_params)
    respond_to do |format|
      if @repositories.present?
        format.js
      else
        puts "Here"
        format.js { flash.now[:notice] = "Something went wrong, please try again!" }
      end
    end
  end

  private

  def set_page_params
    params[:per_page] = RESULTS_PER_PAGE
    params[:page] = 1 if params[:page].blank?
  end

  def check_required_params
    if params[:query].blank?
      flash.now[:notice] = "Please enter a search term"
      render :index
    end
  end

  def search_params
    params.permit(:query, :page, :per_page)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/github/repositories_helper.rb
module Github::RepositoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/github/repositories/index.js.erb
<% if @repositories %>
  $('#repos-table').
    html("<%= j (render 'home/repos-table', repositories: @repositories, page: @page, query: @query) %>");
<% else %>
  $("#flash").html('<%= j render partial: "shared/notice_banner" %>');
<% end %>

app/views/home/_repos-table.html.erb
<div>
  <table>
    <thead>
      <tr>
        <th>Name</th>
      </tr>
    </thead>
    <tbody>
    <% repositories.each do |repository| %>
      <tr>
        <td><a href="<%= repository['html_url'] %>" target='_blank'><%= repository['name'] %></a> </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>
<%if repositories.length > 0 %>
  <%= link_to "&laquo; Previous".html_safe, github_repositories_path(page: page - 1, query: query), class: "previous", remote: true %>
  <%= link_to "&raquo; Next".html_safe, github_repositories_path(page: page + 1, query: query), class: "next", remote: true %>
<% end %>

app/views/home/index.html.erb
<h1>Search Github public repositories</h1>
<%= form_tag github_repositories_path, :method => 'get', remote: true do %>
  <%= text_field_tag :query, params[:query] %>
  <%= submit_tag("Search", :name => nil) %>
<%end%>
 <div id="repos-table">
  <%= render 'repos-table', repositories: [], page: 1 %>
</div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GithubRepoSearch</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <div id="flash">
    <% if notice.present? %>
      <%= render partial: "shared/notice_banner" %>
    <% end %>
    </div>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_notice_banner.html.erb
<div class="alert alert-danger">
  <%= notice %>
  <a href="#" class="close">&times;</a>
</div>